#Site Settings
title: Ocean Data Academy
author:
  name: Kylie Kinne
  email: kykinne@ucsd.edu
description: A starting place for analyzing physical oceanography data
logo: /assets/img/2023-08-14 Drone Greenland_0074_.jpg

#Built Settings
#theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme 

#show_downloads: true 
#google_analytics: [Your Google Analytics tracking ID]
